plugins { id 'com.android.application' }

android {
    namespace 'in.nammamoi.webwrapper'
    compileSdk 35
    defaultConfig {
        applicationId 'in.nammamoi.webwrapper'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies { implementation 'androidx.activity:activity:1.9.2' }
